- project:
    check: &jobs
      jobs:
        - run-test-command:
            vars:
              test_command:
                - cabal build -O0 --enable-tests
                - cabal test  -O0 --test-show-details=direct
            nodeset:
              nodes:
                - name: container
                  label: zuul-worker-haskell-ghc9
        - hlint:
            nodeset:
              nodes:
                - name: container
                  label: zuul-worker-haskell-ghc9
    gate: *jobs
